// Copyright (c) 2023 Álvaro Ceballos
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE or copy at http://www.boost.org/LICENSE_1_0.txt)

#ifndef ERYTHRONELUMBO_MAIHUENIA_DETAIL_PREPROCESSOR_HPP
#define ERYTHRONELUMBO_MAIHUENIA_DETAIL_PREPROCESSOR_HPP


#include <erythronelumbo/maihuenia/version.hpp>
#include <erythronelumbo/maihuenia/config.hpp>


#define ERYTHRONELUMBO_MAIHUENIA_PP_IDENTITY(x) x

#define ERYTHRONELUMBO_MAIHUENIA_PP_UNPACK(...) __VA_ARGS__

#define ERYTHRONELUMBO_MAIHUENIA_PP_UNPACK_1(...) \
ERYTHRONELUMBO_MAIHUENIA_PP_UNPACK(__VA_ARGS__)

#define ERYTHRONELUMBO_MAIHUENIA_PP_UNPACK_2(...) \
ERYTHRONELUMBO_MAIHUENIA_PP_UNPACK_1(__VA_ARGS__)

#define ERYTHRONELUMBO_MAIHUENIA_PP_UNPACK_3(...) \
ERYTHRONELUMBO_MAIHUENIA_PP_UNPACK_2(__VA_ARGS__)

#define ERYTHRONELUMBO_MAIHUENIA_PP_UNPACK_4(...) \
ERYTHRONELUMBO_MAIHUENIA_PP_UNPACK_3(__VA_ARGS__)

#define ERYTHRONELUMBO_MAIHUENIA_PP_UNPACK_5(...) \
ERYTHRONELUMBO_MAIHUENIA_PP_UNPACK_4(__VA_ARGS__)


#define ERYTHRONELUMBO_MAIHUENIA_PP_EAT(...)

#define ERYTHRONELUMBO_MAIHUENIA_PP_EMPTY()
#define ERYTHRONELUMBO_MAIHUENIA_PP_COMMA() ERYTHRONELUMBO_MAIHUENIA_PP_COMMA_()
#define ERYTHRONELUMBO_MAIHUENIA_PP_COMMA_() ,
#define ERYTHRONELUMBO_MAIHUENIA_PP_SEMICOLON() ;
#define ERYTHRONELUMBO_MAIHUENIA_PP_MEM_ACC_OP() ::



#define ERYTHRONELUMBO_MAIHUENIA_PP_DEFER(f) \
f ERYTHRONELUMBO_MAIHUENIA_PP_EMPTY()

#define ERYTHRONELUMBO_MAIHUENIA_PP_CONCAT_(a, b) a##b

#define ERYTHRONELUMBO_MAIHUENIA_PP_CONCAT(a, b) \
ERYTHRONELUMBO_MAIHUENIA_PP_CONCAT_(a, b)


#define ERYTHRONELUMBO_MAIHUENIA_PP_NOT_IMPL_0 1
#define ERYTHRONELUMBO_MAIHUENIA_PP_NOT_IMPL_1 0

#define ERYTHRONELUMBO_MAIHUENIA_PP_NOT(x) \
ERYTHRONELUMBO_MAIHUENIA_PP_CONCAT( \
  ERYTHRONELUMBO_MAIHUENIA_PP_NOT_IMPL_, x \
)

#define ERYTHRONELUMBO_MAIHUENIA_PP_OR_IMPL_0_0 0
#define ERYTHRONELUMBO_MAIHUENIA_PP_OR_IMPL_0_1 1
#define ERYTHRONELUMBO_MAIHUENIA_PP_OR_IMPL_1_0 1
#define ERYTHRONELUMBO_MAIHUENIA_PP_OR_IMPL_1_1 1

#define ERYTHRONELUMBO_MAIHUENIA_PP_OR_IMPL(a, b) \
ERYTHRONELUMBO_MAIHUENIA_PP_OR_IMPL_##a##_##b

#define ERYTHRONELUMBO_MAIHUENIA_PP_OR(a, b) \
ERYTHRONELUMBO_MAIHUENIA_PP_OR_IMPL(a, b)

#define ERYTHRONELUMBO_MAIHUENIA_PP_AND_IMPL_0_0 0
#define ERYTHRONELUMBO_MAIHUENIA_PP_AND_IMPL_0_1 0
#define ERYTHRONELUMBO_MAIHUENIA_PP_AND_IMPL_1_0 0
#define ERYTHRONELUMBO_MAIHUENIA_PP_AND_IMPL_1_1 1

#define ERYTHRONELUMBO_MAIHUENIA_PP_AND_IMPL(a, b) \
ERYTHRONELUMBO_MAIHUENIA_PP_AND_IMPL_##a##_##b

#define ERYTHRONELUMBO_MAIHUENIA_PP_AND(a, b) \
ERYTHRONELUMBO_MAIHUENIA_PP_AND_IMPL(a, b)

#define ERYTHRONELUMBO_MAIHUENIA_PP_COMMA_IF_0
#define ERYTHRONELUMBO_MAIHUENIA_PP_COMMA_IF_1 ,

#define ERYTHRONELUMBO_MAIHUENIA_PP_COMMA_IF(cond) \
ERYTHRONELUMBO_MAIHUENIA_PP_CONCAT( \
  ERYTHRONELUMBO_MAIHUENIA_PP_COMMA_IF_, cond \
)


#define ERYTHRONELUMBO_MAIHUENIA_PP_SECOND_(a, b, ...) b

#define ERYTHRONELUMBO_MAIHUENIA_PP_TEST(x) \
ERYTHRONELUMBO_MAIHUENIA_PP_SECOND_(x, 0)

#define ERYTHRONELUMBO_MAIHUENIA_PP_IS_TRUE(...) ~, 1

#define ERYTHRONELUMBO_MAIHUENIA_PP_IS_ZERO_0 ~, 1

#define ERYTHRONELUMBO_MAIHUENIA_PP_IS_ZERO(x) \
ERYTHRONELUMBO_MAIHUENIA_PP_TEST( \
  ERYTHRONELUMBO_MAIHUENIA_PP_CONCAT(ERYTHRONELUMBO_MAIHUENIA_PP_IS_ZERO_, x) \
)


#define ERYTHRONELUMBO_MAIHUENIA_PP_IF(c) \
ERYTHRONELUMBO_MAIHUENIA_PP_CONCAT(ERYTHRONELUMBO_MAIHUENIA_PP_IF_, c)

#define ERYTHRONELUMBO_MAIHUENIA_PP_IF_0(...) ERYTHRONELUMBO_MAIHUENIA_PP_ELSE_0

#define ERYTHRONELUMBO_MAIHUENIA_PP_IF_1(...) \
__VA_ARGS__ ERYTHRONELUMBO_MAIHUENIA_PP_ELSE_1

#define ERYTHRONELUMBO_MAIHUENIA_PP_ELSE_0(...) __VA_ARGS__

#define ERYTHRONELUMBO_MAIHUENIA_PP_ELSE_1(...)


#define ERYTHRONELUMBO_MAIHUENIA_PP_VA_HEAD(...) \
ERYTHRONELUMBO_MAIHUENIA_PP_VA_HEAD_IMPL(__VA_ARGS__, _)

#define ERYTHRONELUMBO_MAIHUENIA_PP_VA_HEAD_IMPL(x, ...) x

#define ERYTHRONELUMBO_MAIHUENIA_PP_VA_TAIL(x, ...) (__VA_ARGS__)


#define ERYTHRONELUMBO_MAIHUENIA_PP_HAS_NO_ARGS(...) \
ERYTHRONELUMBO_MAIHUENIA_PP_TEST(ERYTHRONELUMBO_MAIHUENIA_PP_VA_HEAD( \
  ERYTHRONELUMBO_MAIHUENIA_PP_IS_TRUE __VA_ARGS__ \
)())


#define ERYTHRONELUMBO_MAIHUENIA_PP_IS_LIST_EMPTY(list) \
ERYTHRONELUMBO_MAIHUENIA_PP_HAS_NO_ARGS list


#include <erythronelumbo/maihuenia/detail/preprocessor/pp_num_args_impl.hpp>
#include <erythronelumbo/maihuenia/detail/preprocessor/pp_for_impl.hpp>
#include <erythronelumbo/maihuenia/detail/preprocessor/pp_at_impl.hpp>
#include <erythronelumbo/maihuenia/detail/preprocessor/pp_transform_impl.hpp>


// Call as `ERYTHRONELUMBO_MAIHUENIA_PP_NUM_ARGS(...)`
#define ERYTHRONELUMBO_MAIHUENIA_PP_NUM_ARGS \
ERYTHRONELUMBO_MAIHUENIA_DETAIL_PP_NUM_ARGS_IMPL


#define ERYTHRONELUMBO_MAIHUENIA_PP_LIST_SIZE(list) \
ERYTHRONELUMBO_MAIHUENIA_PP_IF( \
  ERYTHRONELUMBO_MAIHUENIA_PP_IS_LIST_EMPTY(list) \
)(0)( \
  ERYTHRONELUMBO_MAIHUENIA_PP_NUM_ARGS list \
)


#define ERYTHRONELUMBO_MAIHUENIA_PP_AT_IMPL(i) \
ERYTHRONELUMBO_MAIHUENIA_PP_CONCAT( \
  ERYTHRONELUMBO_MAIHUENIA_DETAIL_PP_AT_IMPL_, i \
)

#define ERYTHRONELUMBO_MAIHUENIA_PP_AT(list, i) \
ERYTHRONELUMBO_MAIHUENIA_PP_AT_IMPL(i) list


#define ERYTHRONELUMBO_MAIHUENIA_PP_FOR_IMPL(f, d, n, x) \
ERYTHRONELUMBO_MAIHUENIA_PP_CONCAT( \
  ERYTHRONELUMBO_MAIHUENIA_DETAIL_PP_FOR_IMPL_, n \
)(f, x, d)

#define ERYTHRONELUMBO_MAIHUENIA_PP_FOR(f, d, n, x) \
ERYTHRONELUMBO_MAIHUENIA_PP_FOR_IMPL( \
  f, ERYTHRONELUMBO_MAIHUENIA_PP_IDENTITY(d), n, x \
)


#define ERYTHRONELUMBO_MAIHUENIA_PP_TRANSFORM_IMPL(f, d, s, x, n) \
ERYTHRONELUMBO_MAIHUENIA_PP_UNPACK( \
  ERYTHRONELUMBO_MAIHUENIA_PP_CONCAT( \
    ERYTHRONELUMBO_MAIHUENIA_DETAIL_PP_TRANSFORM_IMPL_, n \
  )( \
    f, d, s, x \
  ) \
)

#define ERYTHRONELUMBO_MAIHUENIA_PP_TRANSFORM(f, list, x, d) \
ERYTHRONELUMBO_MAIHUENIA_PP_TRANSFORM_( \
  f, list, x, d \
)

#define ERYTHRONELUMBO_MAIHUENIA_PP_TRANSFORM_(f, list, x, d) \
ERYTHRONELUMBO_MAIHUENIA_PP_IF( \
  ERYTHRONELUMBO_MAIHUENIA_PP_IS_LIST_EMPTY(list) \
)()( \
  ERYTHRONELUMBO_MAIHUENIA_PP_TRANSFORM_IMPL( \
    f, d, list, x, ERYTHRONELUMBO_MAIHUENIA_PP_LIST_SIZE(list) \
  ) \
)


#define ERYTHRONELUMBO_MAIHUENIA_DETAIL_NSP_OP(item, x) namespace item {
#define ERYTHRONELUMBO_MAIHUENIA_DETAIL_NSP_CL(item, x) }

#define ERYTHRONELUMBO_MAIHUENIA_DETAIL_NO_TRFM(item, x) item

#define ERYTHRONELUMBO_MAIHUENIA_DETAIL_MEM_ACC_MANY(ms) \
ERYTHRONELUMBO_MAIHUENIA_PP_TRANSFORM( \
  ERYTHRONELUMBO_MAIHUENIA_DETAIL_NO_TRFM, \
  ms, ~, ERYTHRONELUMBO_MAIHUENIA_PP_MEM_ACC_OP \
)


#endif // ERYTHRONELUMBO_MAIHUENIA_DETAIL_PREPROCESSOR_HPP
